name             'php-dev'
maintainer       'Alex Willemsma'
maintainer_email 'alex@undergroundwebdevelopment.com'
license          'Public Domain'
description      'Installs/Configures php-dev'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'

depends          'apt'
depends          'git'
depends          'build-essential'
depends          'vim'
depends          'ssh'
depends          'php'
depends          'mysql'
depends          'apache2'
